### ISSUE TITLE
Error: Task exception was never retrieved

### ISSUE THREAD

**Issue by huffynulled** [Mehul343/PokeGrinder#17]
Not sure why but the program was running smoothly until the following error occurred. https://imgur.com/sjzBWn2

`Task exception was never retrieved
future: <Task finished name='Task-22410' coro=<timer() done, defined at E:\Downloads\HFPokeBot\PokeGrinder-main\main.py:43> exception=ClientOSError(22, 'The semaphore timeout period has expired', None, 121, None)>
Traceback (most recent call last):
  File "E:\Downloads\HFPokeBot\PokeGrinder-main\main.py", line 45, in timer
    await after.channel.send(";p")
  File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\abc.py", line 1061, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 240, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 544, in _request
    await resp.start(conn)
  File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 121] The semaphore timeout period has expired`

**Comment by Mehul343** [comment]
This 

> Not sure why but the program was running smoothly until the following error occurred. https://imgur.com/sjzBWn2
> 
> `Task exception was never retrieved future: <Task finished name='Task-22410' coro=<timer() done, defined at E:\Downloads\HFPokeBot\PokeGrinder-main\main.py:43> exception=ClientOSError(22, 'The semaphore timeout period has expired', None, 121, None)> Traceback (most recent call last): File "E:\Downloads\HFPokeBot\PokeGrinder-main\main.py", line 45, in timer await after.channel.send(";p") File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\abc.py", line 1061, in send data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 240, in request async with self.__session.request(method, url, **kwargs) as r: File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__ self._resp = await self._coro File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 544, in _request await resp.start(conn) File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 890, in start message, payload = await self._protocol.read() # type: ignore File "C:\Users\Rui\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\streams.py", line 604, in read await self._waiter aiohttp.client_exceptions.ClientOSError: [WinError 121] The semaphore timeout period has expired`

This error is on your end, try using a different Python Version.

**Comment by Mehul343** [comment]
No replies within 8 days. Closing this issue due to inactivity.
